/**
 * build-catalog.ts: real automation, committed as source.
 *
 * Reads the repo's actual egg JSON file(s) and emits src/data/catalog.json,
 * which the docs site imports. Nothing about the site's egg/variable/engine
 * content is hand-written: it is all derived from the exported egg.
 *
 * Run: bun scripts/build-catalog.ts   (also runs as part of `bun run build`)
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dir = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dir, "..", "..");
const OUT = resolve(__dir, "..", "src", "data", "catalog.json");

interface EggVariable {
  name: string;
  description: string;
  env_variable: string;
  default_value: string;
  user_viewable: boolean;
  user_editable: boolean;
  rules: string;
  field_type: string;
}

interface EggJson {
  meta: { version: string; update_url: string };
  exported_at: string;
  name: string;
  author: string;
  description: string;
  features?: string[];
  docker_images: Record<string, string>;
  startup: string;
  variables: EggVariable[];
}

interface Engine {
  name: string;
  alias?: string;
}

interface EngineCategory {
  category: string;
  engines: Engine[];
}

/** Parse the `DATABASE_TYPE` variable description into engine categories.
 * Lines look like `SQL: mariadb, mysql, postgresql` and a line may bundle a
 * second list after a `|` (e.g. `... kafka | Misc: sqld, custom`). */
function parseEngines(dbTypeVar: EggVariable | undefined): EngineCategory[] {
  if (!dbTypeVar) return [];
  const categories: EngineCategory[] = [];
  for (const rawLine of dbTypeVar.description.split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith("Versions:") || line.includes("Invalid/")) continue;
    for (const segment of line.split("|")) {
      const seg = segment.trim();
      const m = seg.match(/^([^:]+):\s*(.+)$/);
      if (!m) continue;
      const category = m[1].trim();
      // Guard against wrapping prose (e.g. theVersions: latest, ... line).
      if (!/^[A-Za-z][A-Za-z0-9 /&+-]*$/.test(category)) continue;
      const engines: Engine[] = m[2]
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean)
        .map((token) => {
          const alias = token.match(/^([a-z0-9-]+)\s*\(\s*([a-z0-9-]+)\s*\)$/);
          if (alias) return { name: alias[1], alias: alias[2] };
          return { name: token };
        });
      if (engines.length > 0) categories.push({ category, engines });
    }
  }
  return categories;
}

/** Discover every exported egg JSON at the repo root (currently exactly one). */
function discoverEggs(): string[] {
  return readdirSync(REPO_ROOT)
    .filter((f) => f.startsWith("egg-") && f.endsWith(".json"))
    .sort();
}

function main() {
  const files = discoverEggs();
  if (files.length === 0) {
    console.error("build-catalog: no egg-*.json found at the repo root");
    process.exit(1);
  }

  const eggs = files.map((file) => {
    const egg: EggJson = JSON.parse(readFileSync(resolve(REPO_ROOT, file), "utf8"));
    const dbTypeVar = egg.variables.find(
      (v) => v.env_variable === "DATABASE_TYPE",
    );
    const categories = parseEngines(dbTypeVar);
    const engines = categories.flatMap((c) => c.engines);
    const engineCount = engines.length;
    const realEngines = engines.filter((e) => e.name !== "custom").length;
    return {
      file,
      name: egg.name,
      author: egg.author,
      description: egg.description,
      metaVersion: egg.meta.version,
      updateUrl: egg.meta.update_url,
      exportedAt: egg.exported_at,
      features: egg.features ?? [],
      dockerImages: Object.entries(egg.docker_images).map(([label, image]) => {
        const tag = image.split(":").pop() || "latest";
        return { label, image, tag };
      }),
      startup: egg.startup,
      variables: egg.variables,
      engineCategories: categories,
      counts: {
        variables: egg.variables.length,
        dockerImages: Object.keys(egg.docker_images).length,
        engines: engineCount,
        realEngines,
      },
    };
  });

  const catalog = {
    _source: "Generated by docs/scripts/build-catalog.ts from the repo's egg JSON - do not edit.",
    repo: {
      url: "https://github.com/PotenFYR-Studios/Database-Eggs",
      rawBase: "https://raw.githubusercontent.com/PotenFYR-Studios/Database-Eggs/master",
      eggFile: files[0],
    },
    counts: {
      eggs: eggs.length,
      dockerImages: eggs.reduce((n, e) => n + e.counts.dockerImages, 0),
      variables: eggs.reduce((n, e) => n + e.counts.variables, 0),
      engines: eggs.reduce((n, e) => n + e.counts.engines, 0),
      realEngines: eggs.reduce((n, e) => n + e.counts.realEngines, 0),
      panels: 5, // Pterodactyl, Pelican, Feather, Wisp, Docker
    },
    eggs,
  };

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, JSON.stringify(catalog, null, 2) + "\n");

  const c = catalog.counts;
  console.log(
    `build-catalog: ${c.eggs} egg(s), ${c.dockerImages} docker image(s), ${c.variables} variables, ${c.engines} engine targets (${c.realEngines} engines + custom)`,
  );
}

main();
